export const CATALOGUED_SYSTEMS = {
  "MYSTIC-1": {
    thumbnail: "img/catalogued/1.png",
    designation: "RS 8513-928-8-5906587-272",
    discDate: "2026.05.06 11:12:57.10",
    discMethod: "Gravitational Microlensing",
    pioneer: "Leon DeFox",
    systemType: "Single",
    parentSun: "N/A",
    spectralClass: "P",
    distToSun: 0.29,
    planetCount: {
      major: 1,
      dwarf: 0,
    },
    moonCount: {
      major: 1,
      dwarf: 2,
    },
    life: {
      exists: false,
      objectsWithLife: 0,
      types: "",
    },
  },
  "MYSTIC-2": {
    thumbnail: "img/catalogued/2.png",
    designation: "RS 8513-928-8-5906587-285",
    discDate: "2026.05.06 11:15:56.64",
    discMethod: "Direct Imaging",
    pioneer: "Leon DeFox",
    systemType: "Binary",
    parentSun: "N/A",
    spectralClass: "M3.9V",
    distToSun: 0.71,
    planetCount: {
      major: 16,
      dwarf: 0,
    },
    moonCount: {
      major: 0,
      dwarf: 0,
    },
    life: {
      exists: false,
      objectsWithLife: 0,
      types: "",
    },
  },
  "MYSTIC-3": {
    thumbnail: "img/catalogued/2.png",
    designation: "RS 8513-928-8-5906586-153",
    discDate: "2026.05.06 11:20:10.78",
    discMethod: "Direct Imaging",
    pioneer: "Leon DeFox",
    systemType: "Binary",
    parentSun: "N/A",
    spectralClass: "M5V",
    distToSun: 0.77,
    planetCount: {
      major: 6,
      dwarf: 1,
    },
    moonCount: {
      major: 0,
      dwarf: 0,
    },
    life: {
      exists: false,
      objectsWithLife: 0,
      types: "",
    },
  },
  "MYSTIC-4": {
    thumbnail: "img/catalogued/2.png",
    designation: "RS 8513-928-8-5906587-88",
    discDate: "2026.05.06 11:21:37.77",
    discMethod: "Direct Imaging",
    pioneer: "Leon DeFox",
    systemType: "Binary",
    parentSun: "N/A",
    spectralClass: "M5.9V",
    distToSun: 0.89,
    planetCount: {
      major: 6,
      dwarf: 0,
    },
    moonCount: {
      major: 0,
      dwarf: 0,
    },
    life: {
      exists: false,
      objectsWithLife: 0,
      types: "",
    },
  },
  "MYSTIC-5": {
    thumbnail: "img/catalogued/2.png",
    designation: "RS 8513-928-8-5906587-89",
    discDate: "2026.05.06 11:21:37.77",
    discMethod: "Gravitational Microlensing",
    pioneer: "Leon DeFox",
    systemType: "Single",
    parentSun: "N/A",
    spectralClass: "P",
    distToSun: 0.93,
    planetCount: {
      major: 1,
      dwarf: 0,
    },
    moonCount: {
      major: 0,
      dwarf: 2,
    },
    life: {
      exists: false,
      objectsWithLife: 0,
      types: "",
    },
  },
  "MYSTIC-6": {
    thumbnail: "img/catalogued/2.png",
    designation: "RS 8513-928-8-5906587-183",
    discDate: "2026.05.06 11:23:56.64",
    discMethod: "Gravitational Microlensing",
    pioneer: "Leon DeFox",
    systemType: "Single",
    parentSun: "N/A",
    spectralClass: "P",
    distToSun: 0.93,
    planetCount: {
      major: 1,
      dwarf: 0,
    },
    moonCount: {
      major: 0,
      dwarf: 0,
    },
    life: {
      exists: false,
      objectsWithLife: 0,
      types: "",
    },
  },
  "MYSTIC-7": {
    thumbnail: "img/catalogued/2.png",
    designation: "RS 8513-928-8-5906586-249",
    discDate: "2026.05.06 11:25:31.05",
    discMethod: "Gravitational Microlensing",
    pioneer: "Leon DeFox",
    systemType: "Single",
    parentSun: "N/A",
    spectralClass: "P",
    distToSun: 1.01,
    planetCount: {
      major: 1,
      dwarf: 0,
    },
    moonCount: {
      major: 0,
      dwarf: 3,
    },
    life: {
      exists: false,
      objectsWithLife: 0,
      types: "",
    },
  },
  "MYSTIC-8": {
    thumbnail: "img/catalogued/2.png",
    designation: "RS 8513-928-8-5906586-45",
    discDate: "2026.05.06 11:26:25.05",
    discMethod: "Gravitational Microlensing",
    pioneer: "Leon DeFox",
    systemType: "Single",
    parentSun: "N/A",
    spectralClass: "P",
    distToSun: 1.1,
    planetCount: {
      major: 1,
      dwarf: 0,
    },
    moonCount: {
      major: 0,
      dwarf: 2,
    },
    life: {
      exists: false,
      objectsWithLife: 0,
      types: "",
    },
  },
  "MYSTIC-9": {
    thumbnail: "img/catalogued/2.png",
    designation: "RS 8513-928-8-5906587-125",
    discDate: "2026.05.06 11:27:42.70",
    discMethod: "Gravitational Microlensing",
    pioneer: "Leon DeFox",
    systemType: "Single",
    parentSun: "N/A",
    spectralClass: "P",
    distToSun: 1.23,
    planetCount: {
      major: 0,
      dwarf: 0,
    },
    moonCount: {
      major: 0,
      dwarf: 0,
    },
    life: {
      exists: false,
      objectsWithLife: 0,
      types: "",
    },
  },
  "MYSTIC-10": {
    thumbnail: "img/catalogued/2.png",
    designation: "RS 8513-928-8-5906586-60",
    discDate: "2026.05.06 11:27:42.70",
    discMethod: "Gravitational Microlensing",
    pioneer: "Leon DeFox",
    systemType: "Single",
    parentSun: "N/A",
    spectralClass: "P",
    distToSun: 1.27,
    planetCount: {
      major: 0,
      dwarf: 0,
    },
    moonCount: {
      major: 0,
      dwarf: 15,
    },
    life: {
      exists: false,
      objectsWithLife: 0,
      types: "",
    },
  },
  "MYSTIC-11": {
    thumbnail: "img/catalogued/2.png",
    designation: "RS 8513-928-8-5906587-373",
    discDate: "2026.05.06 11:29:51.21",
    discMethod: "Direct Imaging",
    pioneer: "Leon DeFox",
    systemType: "Single",
    parentSun: "N/A",
    spectralClass: "M4.1V",
    distToSun: 1.16,
    planetCount: {
      major: 7,
      dwarf: 0,
    },
    moonCount: {
      major: 0,
      dwarf: 0,
    },
    life: {
      exists: false,
      objectsWithLife: 0,
      types: "",
    },
  },
  "MYSTIC-12": {
    thumbnail: "img/catalogued/2.png",
    designation: "RS 8513-928-8-5906587-214",
    discDate: "2026.05.06 11:31:18.44",
    discMethod: "Gravitational Microlensing",
    pioneer: "Leon DeFox",
    systemType: "Single",
    parentSun: "N/A",
    spectralClass: "P",
    distToSun: 1.56,
    planetCount: {
      major: 1,
      dwarf: 0,
    },
    moonCount: {
      major: 0,
      dwarf: 0,
    },
    life: {
      exists: false,
      objectsWithLife: 0,
      types: "",
    },
  },
  "MYSTIC-13": {
    thumbnail: "img/catalogued/2.png",
    designation: "RS 8513-928-8-5906586-165",
    discDate: "2026.05.06 11:32:20.94",
    discMethod: "Direct Imaging",
    pioneer: "Leon DeFox",
    systemType: "Binary",
    parentSun: "N/A",
    spectralClass: "M5.9V",
    distToSun: 1.45,
    planetCount: {
      major: 12,
      dwarf: 0,
    },
    moonCount: {
      major: 0,
      dwarf: 0,
    },
    life: {
      exists: false,
      objectsWithLife: 0,
      types: "",
    },
  },
  "MYSTIC-14": {
    thumbnail: "img/catalogued/2.png",
    designation: "RS 8513-928-8-5906586-89",
    discDate: "2026.05.06 11:34:01.02",
    discMethod: "Direct Imaging",
    pioneer: "Leon DeFox",
    systemType: "Binary",
    parentSun: "N/A",
    spectralClass: "P",
    distToSun: 1.52,
    planetCount: {
      major: 1,
      dwarf: 0,
    },
    moonCount: {
      major: 1,
      dwarf: 0,
    },
    life: {
      exists: false,
      objectsWithLife: 0,
      types: "",
    },
  },
  "MYSTIC-15": {
    thumbnail: "img/catalogued/2.png",
    designation: "Wolf 562",
    discDate: "2026.05.06 11:34:01.02",
    discMethod: "Direct Imaging",
    pioneer: "Leon DeFox",
    systemType: "Single",
    parentSun: "N/A",
    spectralClass: "M3V",
    distToSun: 1.5,
    planetCount: {
      major: 4,
      dwarf: 0,
    },
    moonCount: {
      major: 0,
      dwarf: 0,
    },
    life: {
      exists: false,
      objectsWithLife: 0,
      types: "",
    },
  },
  "MYSTIC-16": {
    thumbnail: "img/catalogued/2.png",
    designation: "RS 8513-928-8-5906586-260",
    discDate: "2026.05.06 11:36:21.57",
    discMethod: "Gravitational Microlensing",
    pioneer: "Leon DeFox",
    systemType: "Single",
    parentSun: "N/A",
    spectralClass: "P",
    distToSun: 1.53,
    planetCount: {
      major: 1,
      dwarf: 0,
    },
    moonCount: {
      major: 0,
      dwarf: 2,
    },
    life: {
      exists: false,
      objectsWithLife: 0,
      types: "",
    },
  },
};

export const PROMISING_WORLDS = {
  Earth: {
    systemName: "Solar System",
    systemType: "Single",
    parentStar: "Sun",
    spectralClass: "G2V",
    distToSun: 6.71,
    type: "Planet",
    moonCount: 1,
    thumbnail: "img/promising/earth.png",
    physical: {
      mass: 1,
      radius: 6371.01,
    },
    orbit: {
      sma: 1.0000010178,
      period: 1,
      eccentricity: 0.0167086342,
    },
    life: {
      exists: true,
      type: "Organic Multicellular (Abiogenesis)",
      biome: "Marine, Terrestrial",
      origin: "Earth",
    },
  },
  "Proxima Centauri b": {
    systemName: "Alpha Centauri",
    systemType: "Triple",
    parentStar: "Proxima Centauri",
    spectralClass: "M5.5V",
    distToSun: 6.29,
    type: "Planet",
    moonCount: 0,
    thumbnail: "img/promising/proximab.png",
    physical: {
      mass: 1.44,
      radius: 7030.16,
    },
    orbit: {
      sma: 0.04848,
      period: 0.0306410959,
      eccentricity: 0.0109,
    },
    life: {
      exists: "pending",
    },
  },
  "Ross 128 b": {
    systemName: "Ross 128 System",
    systemType: "Single",
    parentStar: "Ross 128",
    spectralClass: "M4V",
    distToSun: 5.95,
    type: "Planet",
    moonCount: 0,
    thumbnail: "img/promising/ross128b.png",
    physical: {
      mass: 1.398493,
      radius: 7387.92,
    },
    orbit: {
      sma: 0.0496,
      period: 0.02701166589,
      eccentricity: 0.116,
    },
    life: {
      exists: "pending",
    },
  },
  "GJ 1061 b": {
    systemName: "GJ 1061 System",
    systemType: "Single",
    parentStar: "GJ 1061",
    spectralClass: "M5.5V",
    distToSun: 9.71,
    type: "Planet",
    moonCount: 0,
    thumbnail: "img/promising/gj1061b.png",
    physical: {
      mass: 1.4592,
      radius: 6731.63,
    },
    orbit: {
      sma: 0.021,
      period: 0.0087871233,
      eccentricity: 0.05,
    },
    life: {
      exists: "pending",
    },
  },
  "GJ 1061 c": {
    systemName: "GJ 1061 System",
    systemType: "Single",
    parentStar: "GJ 1061",
    spectralClass: "M5.5V",
    distToSun: 9.71,
    type: "Planet",
    moonCount: 0,
    thumbnail: "img/promising/gj1061c.png",
    physical: {
      mass: 1.7767,
      radius: 7686.91,
    },
    orbit: {
      sma: 0.0342,
      period: 0.0183071233,
      eccentricity: 0.05,
    },
    life: {
      exists: "pending",
    },
  },
  "Luyten b": {
    systemName: "Luyten's System",
    systemType: "Single",
    parentStar: "Luyten's Star",
    spectralClass: "M3.5V",
    distToSun: 9.5,
    type: "Planet",
    moonCount: 0,
    thumbnail: "img/promising/luytenb.png",
    physical: {
      mass: 2.930479,
      radius: 8875.03,
    },
    orbit: {
      sma: 0.09,
      period: 0.05103462995,
      eccentricity: 0.03,
    },
    life: {
      exists: "pending",
    },
  },
  "Teegarden b": {
    systemName: "Teegarden's System",
    systemType: "Single",
    parentStar: "Teegarden's Star",
    spectralClass: "M6V",
    distToSun: 10.34,
    type: "Planet",
    moonCount: 0,
    thumbnail: "img/promising/teegardenb.png",
    physical: {
      mass: 2.6254,
      radius: 8354.69,
    },
    orbit: {
      sma: 0.0259,
      period: 0.01343311407,
      eccentricity: 0.03,
    },
    life: {
      exists: "pending",
    },
  },
  "Teegarden c": {
    systemName: "Teegarden's System",
    systemType: "Single",
    parentStar: "Teegarden's Star",
    spectralClass: "M6V",
    distToSun: 10.34,
    type: "Planet",
    moonCount: 0,
    thumbnail: "img/promising/teegardenc.png",
    physical: {
      mass: 2.3096,
      radius: 8023.93,
    },
    orbit: {
      sma: 0.0455,
      period: 0.03125597293,
      eccentricity: 0.04,
    },
    life: {
      exists: "pending",
    },
  },
  "Wolf 1061 d": {
    systemName: "Wolf 1061 System",
    systemType: "Single",
    parentStar: "Wolf 1061",
    spectralClass: "M3V",
    distToSun: 2.85,
    type: "Planet",
    moonCount: 0,
    thumbnail: "img/promising/wolf1061d.png",
    physical: {
      mass: 7.7,
      radius: 14070.92,
    },
    orbit: {
      sma: 0.047,
      period: 0.594701286,
      eccentricity: 0.55,
    },
    life: {
      exists: "pending",
    },
  },
  "GJ 1002 b": {
    systemName: "GJ 1002 System",
    systemType: "Single",
    parentStar: "GJ 1002",
    spectralClass: "M5.5V",
    distToSun: 10.17,
    type: "Planet",
    moonCount: 0,
    thumbnail: "img/promising/gj1002b.png",
    physical: {
      mass: 1.08188,
      radius: 7219.11,
    },
    orbit: {
      sma: 0.0457,
      period: 0.0283465753,
      eccentricity: 0,
    },
    life: {
      exists: "pending",
    },
  },
  "GJ 1002 c": {
    systemName: "GJ 1002 System",
    systemType: "Single",
    parentStar: "GJ 1002",
    spectralClass: "M5.5V",
    distToSun: 10.17,
    type: "Planet",
    sma: 0.0738,
    moonCount: 0,
    thumbnail: "img/promising/gj1002c.png",
    physical: {
      mass: 1.361896,
      radius: 7470.76,
    },
    orbit: {
      sma: 0.0738,
      period: 0.0580876712,
      eccentricity: 0,
    },
    life: {
      exists: "pending",
    },
  },
  "Gliese 667 C c": {
    systemName: "Gliese 667 System",
    systemType: "Triple",
    parentStar: "Gliese 667 C",
    spectralClass: "M1.5V",
    distToSun: 4.73,
    type: "Planet",
    moonCount: 0,
    thumbnail: "img/promising/gj667cc.png",
    physical: {
      mass: 3.814072,
      radius: 9981.58,
    },
    orbit: {
      sma: 0.125,
      period: 0.0770958904,
      eccentricity: 0.02,
    },
    life: {
      exists: "pending",
    },
  },
  "Gliese 667 C f": {
    systemName: "Gliese 667 System",
    systemType: "Triple",
    parentStar: "Gliese 667 C",
    spectralClass: "M1.5V",
    distToSun: 4.73,
    type: "Planet",
    sma: 0.156,
    moonCount: 0,
    thumbnail: "img/promising/gj667cf.png",
    physical: {
      mass: 2.7047,
      radius: 9026.36,
    },
    orbit: {
      sma: 0.156,
      period: 0.1069205479,
      eccentricity: 0.03,
    },
    life: {
      exists: "pending",
    },
  },
  "Wolf 1069 b": {
    systemName: "Wolf 1069 System",
    systemType: "Single",
    parentStar: "Wolf 1069",
    spectralClass: "M5V",
    distToSun: 10.45,
    type: "Planet",
    moonCount: 0,
    thumbnail: "img/promising/wolf1069b.png",
    physical: {
      mass: 1.260072,
      radius: 8267.29,
    },
    orbit: {
      sma: 0.0672,
      period: 0.04261282084,
      eccentricity: 0,
    },
    life: {
      exists: "pending",
    },
  },
  "Gliese 12 b": {
    systemName: "Gliese 12 System",
    systemType: "Single",
    parentStar: "Gliese 12",
    spectralClass: "M3V",
    distToSun: 16.86,
    type: "Planet",
    moonCount: 0,
    thumbnail: "img/promising/gj12b.png",
    physical: {
      mass: 0.708782,
      radius: 5925.03,
    },
    orbit: {
      sma: 0.0668,
      period: 0.034962789,
      eccentricity: 0.24,
    },
    life: {
      exists: "pending",
    },
  },
  "TRAPPIST-1 d": {
    systemName: "TRAPPIST-1 System",
    systemType: "Single",
    parentStar: "TRAPPIST-1",
    spectralClass: "M8V",
    distToSun: 15.53,
    type: "Planet",
    moonCount: 0,
    thumbnail: "img/promising/trappist1d.png",
    physical: {
      mass: 0.388,
      radius: 5020.35,
    },
    orbit: {
      sma: 0.02227,
      period: 0.0110937507,
      eccentricity: 0.00837,
    },
    life: {
      exists: "pending",
    },
  },
  "TRAPPIST-1 e": {
    systemName: "TRAPPIST-1 System",
    systemType: "Single",
    parentStar: "TRAPPIST-1",
    spectralClass: "M8V",
    distToSun: 15.53,
    type: "Planet",
    moonCount: 0,
    thumbnail: "img/promising/trappist1e.png",
    physical: {
      mass: 0.692,
      radius: 5852.32,
    },
    orbit: {
      sma: 0.02817,
      period: 0.016711274,
      eccentricity: 0.0051,
    },
    life: {
      exists: "pending",
    },
  },
  "TRAPPIST-1 f": {
    systemName: "TRAPPIST-1 System",
    systemType: "Single",
    parentStar: "TRAPPIST-1",
    spectralClass: "M8V",
    distToSun: 15.53,
    type: "Planet",
    moonCount: 0,
    thumbnail: "img/promising/trappist1f.png",
    physical: {
      mass: 1.039,
      radius: 6634.37,
    },
    orbit: {
      sma: 0.0371,
      period: 0.0252238082,
      eccentricity: 0.01007,
    },
    life: {
      exists: "pending",
    },
  },
  "TRAPPIST-1 g": {
    systemName: "TRAPPIST-1 System",
    systemType: "Single",
    parentStar: "TRAPPIST-1",
    spectralClass: "M8V",
    distToSun: 15.53,
    type: "Planet",
    moonCount: 0,
    thumbnail: "img/promising/trappist1g.png",
    physical: {
      mass: 1.321,
      radius: 7185.79,
    },
    orbit: {
      sma: 0.0451,
      period: 0.0338436712,
      eccentricity: 0.00208,
    },
    life: {
      exists: "pending",
    },
  },
  Najma: {
    altName: "Majriti VI",
    systemName: "Upsilon Andromedae System",
    systemType: "Binary",
    parentStar: "Titawin",
    spectralClass: "F8V",
    distToSun: 18.42,
    type: "Moon",
    parent: "Majriti",
    moonCount: 0,
    thumbnail: "img/promising/najma.png",
    physical: {
      mass: 1.15805137,
      radius: 6714.81,
    },
    orbit: {
      sma: 0.0225061535,
      period: 0.0342277585,
      eccentricity: 0.0198265591,
    },
    life: {
      exists: "pending",
    },
  },
  "LHS 1140 b": {
    systemName: "LHS 1140 System",
    systemType: "Single",
    parentStar: "LHS 1140",
    spectralClass: "M4.5V",
    distToSun: 20.01,
    type: "Planet",
    moonCount: 0,
    thumbnail: "img/promising/lhs1140b.png",
    physical: {
      mass: 5.6,
      radius: 11022.0,
    },
    orbit: {
      sma: 0.0957,
      period: 0.06772859721,
      eccentricity: 0.096,
    },
    life: {
      exists: "pending",
    },
  },
  "TOI-1452 b": {
    systemName: "TOI-1452 System",
    systemType: "Single",
    parentStar: "TOI-1452",
    spectralClass: "M4V",
    distToSun: 29.92,
    type: "Planet",
    moonCount: 0,
    thumbnail: "img/promising/toi1452b.png",
    physical: {
      mass: 4.82,
      radius: 10664.25,
    },
    orbit: {
      sma: 0.061,
      period: 0.03028657808,
      eccentricity: 0,
    },
    life: {
      exists: "pending",
    },
  },
  "TOI-700 e": {
    systemName: "TOI-700 System",
    systemType: "Single",
    parentStar: "TOI-700",
    spectralClass: "M2V",
    distToSun: 34.01,
    type: "Planet",
    moonCount: 0,
    thumbnail: "img/promising/toi700e.png",
    physical: {
      mass: 0.43869,
      radius: 6056.47,
    },
    orbit: {
      sma: 0.134,
      period: 0.07614065618,
      eccentricity: 0.059,
    },
    life: {
      exists: "pending",
    },
  },
  "TOI-700 d": {
    systemName: "TOI-700 System",
    systemType: "Single",
    parentStar: "TOI-700",
    spectralClass: "M2V",
    distToSun: 34.01,
    type: "Planet",
    moonCount: 0,
    thumbnail: "img/promising/toi700d.png",
    physical: {
      mass: 2.415579,
      radius: 6820.91,
    },
    orbit: {
      sma: 0.1633,
      period: 0.1024634093,
      eccentricity: 0.042,
    },
    life: {
      exists: "pending",
    },
  },
  "LP 890-9 c": {
    systemName: "LP 890-9 System",
    systemType: "Single",
    parentStar: "LP 890-9",
    spectralClass: "M6V",
    distToSun: 38.4,
    type: "Planet",
    moonCount: 0,
    thumbnail: "img/promising/lp8909c.png",
    physical: {
      mass: 25.32872,
      radius: 8722.02,
    },
    orbit: {
      sma: 0.03984,
      period: 0.02315576687,
      eccentricity: 0,
    },
    life: {
      exists: "pending",
    },
  },
  "TOI-715 b": {
    systemName: "TOI-715 System",
    systemType: "Single",
    parentStar: "TOI-1452",
    spectralClass: "M4V",
    distToSun: 44.11,
    type: "Planet",
    moonCount: 0,
    thumbnail: "img/promising/toi715b.png",
    physical: {
      mass: 1.3666,
      radius: 9837.41,
    },
    orbit: {
      sma: 0.083,
      period: 0.05280880615,
      eccentricity: 0,
    },
    life: {
      exists: "pending",
    },
  },
  "Kepler-1649 c": {
    systemName: "Kepler-1649 System",
    systemType: "Single",
    parentStar: "Kepler-1649",
    spectralClass: "M5V",
    distToSun: 89.56,
    type: "Planet",
    moonCount: 0,
    thumbnail: "img/promising/kepler1649c.png",
    physical: {
      mass: 0.6285,
      radius: 6763.45,
    },
    orbit: {
      sma: 0.0830175519,
      period: 0.05348579803,
      eccentricity: 0,
    },
    life: {
      exists: "pending",
    },
  },
  "Kepler-186 f": {
    systemName: "Kepler-186 System",
    systemType: "Single",
    parentStar: "Kepler-186",
    spectralClass: "M1V",
    distToSun: 176.07,
    type: "Planet",
    moonCount: 0,
    thumbnail: "img/promising/kepler186f.png",
    physical: {
      mass: 1.44,
      radius: 7426.53,
    },
    orbit: {
      sma: 0.432,
      period: 0.355775164,
      eccentricity: 0.04,
    },
    life: {
      exists: "pending",
    },
  },
  "Kepler-296 A e": {
    systemName: "Kepler-296 System",
    systemType: "Binary",
    parentStar: "Kepler-296 A",
    spectralClass: "M1V",
    distToSun: 223.03,
    type: "Planet",
    moonCount: 0,
    thumbnail: "img/promising/kepler296ae.png",
    physical: {
      mass: 5.7548,
      radius: 11152.75,
    },
    orbit: {
      sma: 0.174,
      period: 0.09347865046,
      eccentricity: 0.33,
    },
    life: {
      exists: "pending",
    },
  },
  "Kepler-1652 b": {
    systemName: "Kepler-1652 System",
    systemType: "Single",
    parentStar: "Kepler-1652",
    spectralClass: "M2V",
    distToSun: 249.52,
    type: "Planet",
    moonCount: 0,
    thumbnail: "img/promising/kepler1652b.png",
    physical: {
      mass: 4.3151,
      radius: 10214.71,
    },
    orbit: {
      sma: 0.1654,
      period: 0.1043067342,
      eccentricity: 0,
    },
    life: {
      exists: "pending",
    },
  },
  Celis: {
    systemName: "Nexus System",
    systemType: "Quadruple",
    parentStar: "Nexus A",
    spectralClass: "G2V",
    distToSun: 301.58,
    type: "Planet",
    moonCount: 1,
    thumbnail: "img/promising/celis.png",
    physical: {
      mass: 3.1,
      radius: 8622.23,
    },
    orbit: {
      sma: 1.08,
      period: 1.05592853,
      eccentricity: 0.0167086342,
    },
    life: {
      exists: "pending",
    },
  },
  Diego: {
    altName: "Astrus II",
    systemName: "Nexus System",
    systemType: "Quadruple",
    parentStar: "Nexus A",
    spectralClass: "G2V",
    distToSun: 301.58,
    type: "Moon",
    parent: "Astrus",
    moonCount: 0,
    physical: {
      mass: 0.012553,
      radius: 1947.79,
    },
    orbit: {
      sma: 0.00419,
      period: 0.00270366592,
      eccentricity: 0.00395,
    },
    thumbnail: "img/promising/diego.png",
    life: {
      exists: "pending",
    },
  },
  "Nexus Legendary": {
    systemName: "Nexus System",
    systemType: "Quadruple",
    parentStar: "Nexus B",
    spectralClass: "K3V",
    distToSun: 301.58,
    type: "Planet",
    moonCount: 2,
    thumbnail: "img/promising/nexuslegendary.png",
    physical: {
      mass: 10.5262604,
      radius: 12023.16,
    },
    orbit: {
      sma: 0.55,
      period: 0.477568055,
      eccentricity: 0.02,
    },
    life: {
      exists: "pending",
    },
  },
  "KOI-4878.01": {
    systemName: "KOI-4878 System",
    systemType: "Single",
    parentStar: "KOI-4878",
    spectralClass: "G6V",
    distToSun: 341.39,
    type: "Planet",
    moonCount: 0,
    thumbnail: "img/promising/koi4878.01.png",
    physical: {
      mass: 0.53457,
      radius: 6498.04,
    },
    orbit: {
      sma: 1.1392,
      period: 1.2301780822,
      eccentricity: 0,
    },
    life: {
      exists: "pending",
    },
  },
  "Kepler-62 e": {
    systemName: "Kepler-62 System",
    systemType: "Single",
    parentStar: "Kepler-62",
    spectralClass: "M0V",
    distToSun: 364.57,
    type: "Planet",
    moonCount: 0,
    thumbnail: "img/promising/kepler62e.png",
    physical: {
      mass: 14.476,
      radius: 11911.19,
    },
    orbit: {
      sma: 0.427,
      period: 0.3350856046,
      eccentricity: 0,
    },
    life: {
      exists: "pending",
    },
  },
  "Kepler-62 f": {
    systemName: "Kepler-62 System",
    systemType: "Single",
    parentStar: "Kepler-62",
    spectralClass: "M0V",
    distToSun: 364.57,
    type: "Planet",
    moonCount: 0,
    thumbnail: "img/promising/kepler62f.png",
    physical: {
      mass: 1.8132,
      radius: 9806.71,
    },
    orbit: {
      sma: 0.718,
      period: 0.7318185232,
      eccentricity: 0,
    },
    life: {
      exists: "pending",
    },
  },
  "Kepler-442 b": {
    systemName: "Kepler-442 System",
    systemType: "Single",
    parentStar: "Kepler-442",
    spectralClass: "KV",
    distToSun: 366.37,
    type: "Planet",
    moonCount: 0,
    thumbnail: "img/promising/kepler442b.png",
    physical: {
      mass: 2.3,
      radius: 8535.85,
    },
    orbit: {
      sma: 0.409,
      period: 0.3074817289,
      eccentricity: 0.04,
    },
    life: {
      exists: "pending",
    },
  },
  Pyron: {
    systemName: "Vesper System",
    systemType: "Single",
    parentStar: "Vesper",
    spectralClass: "G5V",
    distToSun: 493.28,
    type: "Planet",
    moonCount: 7,
    thumbnail: "img/promising/pyron.png",
    physical: {
      mass: 10.0430927,
      radius: 11867.81,
    },
    orbit: {
      sma: 1.6,
      period: 2.00296894,
      eccentricity: 0.040092772,
    },
    life: {
      exists: "pending",
    },
  },
  Orval: {
    systemName: "Nebulous System",
    systemType: "Single",
    parentStar: "Nebulous",
    spectralClass: "M5.9V",
    distToSun: 594.98,
    type: "Planet",
    moonCount: 0,
    thumbnail: "img/promising/orval.png",
    physical: {
      mass: 0.585096,
      radius: 5512.63,
    },
    orbit: {
      sma: 0.0108771254,
      period: 2.00296894,
      eccentricity: 0.0211,
    },
    life: {
      exists: "pending",
    },
  },
  Satyr: {
    systemName: "Lilith System",
    systemType: "Quadruple",
    parentStar: "Khepri",
    spectralClass: "K8.2V",
    distToSun: 862760.026,
    type: "Planet",
    moonCount: 0,
    thumbnail: "img/promising/satyr.png",
    physical: {
      mass: 3.78445816,
      radius: 9098.11,
    },
    orbit: {
      sma: 0.415260489,
      period: 0.359251342,
      eccentricity: 0.0723453645,
    },
    life: {
      exists: "pending",
    },
  },
  Drakara: {
    systemName: "Keryx System",
    systemType: "Triple",
    parentStar: "Sentinel",
    spectralClass: "K4.4V",
    distToSun: 38035958.5,
    type: "Planet",
    moonCount: 1,
    thumbnail: "img/promising/drakara.png",
    physical: {
      mass: 1.5,
      radius: 7089.29,
    },
    orbit: {
      sma: 0.313517529,
      period: 0.212933395,
      eccentricity: 0.000566026643,
    },
    life: {
      exists: "pending",
    },
  },
  Altan: {
    systemName: "Keryx System",
    systemType: "Triple",
    parentStar: "Sentinel",
    spectralClass: "K4.4V",
    distToSun: 38035958.5,
    type: "Planet",
    moonCount: 0,
    thumbnail: "img/promising/altan.png",
    physical: {
      mass: 0.920000017,
      radius: 6214.55,
    },
    orbit: {
      sma: 0.415260489,
      period: 0.324588049,
      eccentricity: 0.0325,
    },
    life: {
      exists: "pending",
    },
  },
  Vague: {
    systemName: "Void System",
    systemType: "Binary",
    parentStar: "Void",
    spectralClass: "X",
    distToSun: 38105993.3,
    type: "Planet",
    moonCount: 0,
    thumbnail: "img/promising/vague.png",
    physical: {
      mass: 3.98152089,
      radius: 6214.55,
    },
    orbit: {
      sma: 47.3431429,
      period: 0.0569803602,
      eccentricity: 0.000244469439,
    },
    life: {
      exists: "pending",
    },
  },
  Verdant: {
    systemName: "Void System",
    systemType: "Binary",
    parentStar: "Essence",
    spectralClass: "G8.8V",
    distToSun: 38105993.3,
    type: "Planet",
    moonCount: 0,
    thumbnail: "img/promising/verdant.png",
    physical: {
      mass: 0.477668345,
      radius: 5208.59,
    },
    orbit: {
      sma: 0.7,
      period: 0.609915173,
      eccentricity: 0.0440898533,
    },
    life: {
      exists: "pending",
    },
  },
};

export const TERRAFORMED_WORLDS = {
  Pholion: {
    altName: "Boreas I",
    systemName: "Nexus System",
    systemType: "Quadruple",
    parentStar: "Nexus B",
    spectralClass: "K3V",
    distToSun: 301.58,
    type: "Moon",
    parent: "Boreas",
    moonCount: 0,
    thumbnail: "img/terraformed/pholion.png",
    physical: {
      radius: 5822.41,
      mass: 0.74,
    },
    orbit: {
      sma: 0.0080000000360968,
      period: 0.00875195357,
      eccentricity: 0.03,
    },
    life: {
      exists: "pending",
    },
  },
};
