// ============================================================
//  PLANETARY ARCHIVE — DATA FILE
//  Replace these example entries with your real JSON data,
//  or load from external JSON files via fetch().
// ============================================================

// ── CATALOGUED SYSTEMS ──────────────────────────────────────
const CATALOGUED_SYSTEMS = {
  "MYSTIC-1": {
    thumbnail: "img/catalogued/1.png",
    designation: "RS 8513-928-8-5906587-272",
    discDate: "2026.05.06 11:12:57.10",
    discMethod: "Gravitational Microlensing",
    pioneer: "Leon DeFox",
    systemType: "Single",
    parentSun: "N/A",
    spectralClass: "P",
    distToSun: 0.29,
    planetCount: {
      major: 1,
      dwarf: 0,
    },
    moonCount: {
      major: 1,
      dwarf: 2,
    },
    life: {
      exists: false,
      objectsWithLife: 0,
      types: "",
    },
  },
  "MYSTIC-2": {
    thumbnail: "img/catalogued/2.png",
    designation: "RS 8513-928-8-5906587-285",
    discDate: "2026.05.06 11:15:56.64",
    discMethod: "Direct Imaging",
    pioneer: "Leon DeFox",
    systemType: "Binary",
    parentSun: "N/A",
    spectralClass: "M3.9V",
    distToSun: 0.71,
    planetCount: {
      major: 16,
      dwarf: 0,
    },
    moonCount: {
      major: 0,
      dwarf: 0,
    },
    life: {
      exists: false,
      objectsWithLife: 0,
      types: "",
    },
  },
  "MYSTIC-3": {
    thumbnail: "img/catalogued/2.png",
    designation: "RS 8513-928-8-5906586-153",
    discDate: "2026.05.06 11:20:10.78",
    discMethod: "Direct Imaging",
    pioneer: "Leon DeFox",
    systemType: "Binary",
    parentSun: "N/A",
    spectralClass: "M5V",
    distToSun: 0.77,
    planetCount: {
      major: 6,
      dwarf: 1,
    },
    moonCount: {
      major: 0,
      dwarf: 0,
    },
    life: {
      exists: false,
      objectsWithLife: 0,
      types: "",
    },
  },
  "MYSTIC-4": {
    thumbnail: "img/catalogued/2.png",
    designation: "RS 8513-928-8-5906587-88",
    discDate: "2026.05.06 11:21:37.77",
    discMethod: "Direct Imaging",
    pioneer: "Leon DeFox",
    systemType: "Binary",
    parentSun: "N/A",
    spectralClass: "M5.9V",
    distToSun: 0.89,
    planetCount: {
      major: 6,
      dwarf: 0,
    },
    moonCount: {
      major: 0,
      dwarf: 0,
    },
    life: {
      exists: false,
      objectsWithLife: 0,
      types: "",
    },
  },
  "MYSTIC-5": {
    thumbnail: "img/catalogued/2.png",
    designation: "RS 8513-928-8-5906587-89",
    discDate: "2026.05.06 11:21:37.77",
    discMethod: "Gravitational Microlensing",
    pioneer: "Leon DeFox",
    systemType: "Single",
    parentSun: "N/A",
    spectralClass: "P",
    distToSun: 0.93,
    planetCount: {
      major: 1,
      dwarf: 0,
    },
    moonCount: {
      major: 0,
      dwarf: 2,
    },
    life: {
      exists: false,
      objectsWithLife: 0,
      types: "",
    },
  },
  "MYSTIC-6": {
    thumbnail: "img/catalogued/2.png",
    designation: "RS 8513-928-8-5906587-183",
    discDate: "2026.05.06 11:23:56.64",
    discMethod: "Gravitational Microlensing",
    pioneer: "Leon DeFox",
    systemType: "Single",
    parentSun: "N/A",
    spectralClass: "P",
    distToSun: 0.93,
    planetCount: {
      major: 1,
      dwarf: 0,
    },
    moonCount: {
      major: 0,
      dwarf: 0,
    },
    life: {
      exists: false,
      objectsWithLife: 0,
      types: "",
    },
  },
  "MYSTIC-7": {
    thumbnail: "img/catalogued/2.png",
    designation: "RS 8513-928-8-5906586-249",
    discDate: "2026.05.06 11:25:31.05",
    discMethod: "Gravitational Microlensing",
    pioneer: "Leon DeFox",
    systemType: "Single",
    parentSun: "N/A",
    spectralClass: "P",
    distToSun: 1.01,
    planetCount: {
      major: 1,
      dwarf: 0,
    },
    moonCount: {
      major: 0,
      dwarf: 3,
    },
    life: {
      exists: false,
      objectsWithLife: 0,
      types: "",
    },
  },
  "MYSTIC-8": {
    thumbnail: "img/catalogued/2.png",
    designation: "RS 8513-928-8-5906586-45",
    discDate: "2026.05.06 11:26:25.05",
    discMethod: "Gravitational Microlensing",
    pioneer: "Leon DeFox",
    systemType: "Single",
    parentSun: "N/A",
    spectralClass: "P",
    distToSun: 1.1,
    planetCount: {
      major: 1,
      dwarf: 0,
    },
    moonCount: {
      major: 0,
      dwarf: 2,
    },
    life: {
      exists: false,
      objectsWithLife: 0,
      types: "",
    },
  },
  "MYSTIC-9": {
    thumbnail: "img/catalogued/2.png",
    designation: "RS 8513-928-8-5906587-125",
    discDate: "2026.05.06 11:27:42.70",
    discMethod: "Gravitational Microlensing",
    pioneer: "Leon DeFox",
    systemType: "Single",
    parentSun: "N/A",
    spectralClass: "P",
    distToSun: 1.23,
    planetCount: {
      major: 0,
      dwarf: 0,
    },
    moonCount: {
      major: 0,
      dwarf: 0,
    },
    life: {
      exists: false,
      objectsWithLife: 0,
      types: "",
    },
  },
  "MYSTIC-10": {
    thumbnail: "img/catalogued/2.png",
    designation: "RS 8513-928-8-5906586-60",
    discDate: "2026.05.06 11:27:42.70",
    discMethod: "Gravitational Microlensing",
    pioneer: "Leon DeFox",
    systemType: "Single",
    parentSun: "N/A",
    spectralClass: "P",
    distToSun: 1.27,
    planetCount: {
      major: 0,
      dwarf: 0,
    },
    moonCount: {
      major: 0,
      dwarf: 15,
    },
    life: {
      exists: false,
      objectsWithLife: 0,
      types: "",
    },
  },
  "MYSTIC-11": {
    thumbnail: "img/catalogued/2.png",
    designation: "RS 8513-928-8-5906587-373",
    discDate: "2026.05.06 11:29:51.21",
    discMethod: "Direct Imaging",
    pioneer: "Leon DeFox",
    systemType: "Single",
    parentSun: "N/A",
    spectralClass: "M4.1V",
    distToSun: 1.16,
    planetCount: {
      major: 7,
      dwarf: 0,
    },
    moonCount: {
      major: 0,
      dwarf: 0,
    },
    life: {
      exists: false,
      objectsWithLife: 0,
      types: "",
    },
  },
  "MYSTIC-12": {
    thumbnail: "img/catalogued/2.png",
    designation: "RS 8513-928-8-5906587-214",
    discDate: "2026.05.06 11:31:18.44",
    discMethod: "Gravitational Microlensing",
    pioneer: "Leon DeFox",
    systemType: "Single",
    parentSun: "N/A",
    spectralClass: "P",
    distToSun: 1.56,
    planetCount: {
      major: 1,
      dwarf: 0,
    },
    moonCount: {
      major: 0,
      dwarf: 0,
    },
    life: {
      exists: false,
      objectsWithLife: 0,
      types: "",
    },
  },
  "MYSTIC-13": {
    thumbnail: "img/catalogued/2.png",
    designation: "RS 8513-928-8-5906586-165",
    discDate: "2026.05.06 11:32:20.94",
    discMethod: "Direct Imaging",
    pioneer: "Leon DeFox",
    systemType: "Binary",
    parentSun: "N/A",
    spectralClass: "M5.9V",
    distToSun: 1.45,
    planetCount: {
      major: 12,
      dwarf: 0,
    },
    moonCount: {
      major: 0,
      dwarf: 0,
    },
    life: {
      exists: false,
      objectsWithLife: 0,
      types: "",
    },
  },
  "MYSTIC-14": {
    thumbnail: "img/catalogued/2.png",
    designation: "RS 8513-928-8-5906586-89",
    discDate: "2026.05.06 11:34:01.02",
    discMethod: "Direct Imaging",
    pioneer: "Leon DeFox",
    systemType: "Binary",
    parentSun: "N/A",
    spectralClass: "P",
    distToSun: 1.52,
    planetCount: {
      major: 1,
      dwarf: 0,
    },
    moonCount: {
      major: 1,
      dwarf: 0,
    },
    life: {
      exists: false,
      objectsWithLife: 0,
      types: "",
    },
  },
  "MYSTIC-15": {
    thumbnail: "img/catalogued/2.png",
    designation: "Wolf 562",
    discDate: "2026.05.06 11:34:01.02",
    discMethod: "Direct Imaging",
    pioneer: "Leon DeFox",
    systemType: "Single",
    parentSun: "N/A",
    spectralClass: "M3V",
    distToSun: 1.5,
    planetCount: {
      major: 4,
      dwarf: 0,
    },
    moonCount: {
      major: 0,
      dwarf: 0,
    },
    life: {
      exists: false,
      objectsWithLife: 0,
      types: "",
    },
  },
  "MYSTIC-16": {
    thumbnail: "img/catalogued/2.png",
    designation: "RS 8513-928-8-5906586-260",
    discDate: "2026.05.06 11:36:21.57",
    discMethod: "Gravitational Microlensing",
    pioneer: "Leon DeFox",
    systemType: "Single",
    parentSun: "N/A",
    spectralClass: "P",
    distToSun: 1.53,
    planetCount: {
      major: 1,
      dwarf: 0,
    },
    moonCount: {
      major: 0,
      dwarf: 2,
    },
    life: {
      exists: false,
      objectsWithLife: 0,
      types: "",
    },
  },
};

// ── PROMISING WORLDS (TERRANIA 2.0 CANDIDATES) ──────────────
const PROMISING_WORLDS = {
  Earth: {
    systemName: "Solar System",
    systemType: "Single",
    parentStar: "Sun",
    spectralClass: "G2V",
    distToSun: 6.71,
    type: "Planet",
    sma: 1.0000010178,
    radius: 6371,
    mass: 1,
    moonCount: 1,
    thumbnail: "img/promising/earth.png",
    life: {
      exists: true,
      type: "Organic Multicellular (Abiogenesis)",
      biome: "Marine, Terrestrial",
      origin: "Earth",
    },
  },
  "Proxima Centauri b": {
    systemName: "Alpha Centauri",
    systemType: "Triple",
    parentStar: "Proxima Centauri",
    spectralClass: "M5.5V",
    distToSun: 6.29,
    type: "Planet",
    sma: 0.04848,
    radius: 7030.16,
    mass: 1.44,
    moonCount: 0,
    thumbnail: "img/promising/proximab.png",
    life: {
      exists: "pending",
    },
  },
  "Ross 128 b": {
    systemName: "Ross 128 System",
    systemType: "Single",
    parentStar: "Ross 128",
    spectralClass: "M4V",
    distToSun: 5.95,
    type: "Planet",
    sma: 0.0496,
    radius: 7387.92,
    mass: 1.398493,
    moonCount: 0,
    thumbnail: "img/promising/ross128b.png",
    life: {
      exists: "pending",
    },
  },
  "GJ 1061 b": {
    systemName: "GJ 1061 System",
    systemType: "Single",
    parentStar: "GJ 1061",
    spectralClass: "M5.5V",
    distToSun: 9.71,
    type: "Planet",
    sma: 0.021,
    radius: 7257.07,
    mass: 1.4592,
    moonCount: 0,
    thumbnail: "img/promising/gj1061b.png",
    life: {
      exists: "pending",
    },
  },
  "GJ 1061 c": {
    systemName: "GJ 1061 System",
    systemType: "Single",
    parentStar: "GJ 1061",
    spectralClass: "M5.5V",
    distToSun: 9.71,
    type: "Planet",
    sma: 0.035,
    radius: 7648.61,
    mass: 1.7767,
    moonCount: 0,
    thumbnail: "img/promising/gj1061c.png",
    life: {
      exists: "pending",
    },
  },
  "Luyten b": {
    systemName: "Luyten's System",
    systemType: "Single",
    parentStar: "Luyten's Star",
    spectralClass: "M3.5V",
    distToSun: 9.5,
    type: "Planet",
    sma: 0.091,
    radius: 8875.03,
    mass: 2.930479,
    moonCount: 0,
    thumbnail: "img/promising/luytenb.png",
    life: {
      exists: "pending",
    },
  },
  "Teegarden b": {
    systemName: "Teegarden's System",
    systemType: "Single",
    parentStar: "Teegarden's Star",
    spectralClass: "M6V",
    distToSun: 10.34,
    type: "Planet",
    sma: 0.0259,
    radius: 8354.69,
    mass: 2.6254,
    moonCount: 0,
    thumbnail: "img/promising/teegardenb.png",
    life: {
      exists: "pending",
    },
  },
  "Teegarden c": {
    systemName: "Teegarden's System",
    systemType: "Single",
    parentStar: "Teegarden's Star",
    spectralClass: "M6V",
    distToSun: 10.34,
    type: "Planet",
    sma: 0.0455,
    radius: 8023.93,
    mass: 2.3096,
    moonCount: 0,
    thumbnail: "img/promising/teegardenc.png",
    life: {
      exists: "pending",
    },
  },
  "Wolf 1061 d": {
    systemName: "Wolf 1061 System",
    systemType: "Single",
    parentStar: "Wolf 1061",
    spectralClass: "M3V",
    distToSun: 2.85,
    type: "Planet",
    sma: 0.47,
    radius: 14070.92,
    mass: 7.7,
    moonCount: 0,
    thumbnail: "img/promising/wolf1061d.png",
    life: {
      exists: "pending",
    },
  },
  "GJ 1002 b": {
    systemName: "GJ 1002 System",
    systemType: "Single",
    parentStar: "GJ 1002",
    spectralClass: "M5.5V",
    distToSun: 10.17,
    type: "Planet",
    sma: 0.0457,
    radius: 7153.24,
    mass: 1.08188,
    moonCount: 0,
    thumbnail: "img/promising/gj1002b.png",
    life: {
      exists: "pending",
    },
  },
  "GJ 1002 c": {
    systemName: "GJ 1002 System",
    systemType: "Single",
    parentStar: "GJ 1002",
    spectralClass: "M5.5V",
    distToSun: 10.17,
    type: "Planet",
    sma: 0.0738,
    radius: 7411.85,
    mass: 1.361896,
    moonCount: 0,
    thumbnail: "img/promising/gj1002c.png",
    life: {
      exists: "pending",
    },
  },
  "Gliese 667 C c": {
    systemName: "Gliese 667 System",
    systemType: "Triple",
    parentStar: "Gliese 667 C",
    spectralClass: "M1.5V",
    distToSun: 15.42,
    type: "Planet",
    sma: 0.125,
    radius: 9414.86,
    mass: 3.814072,
    moonCount: 0,
    thumbnail: "img/promising/gj667cc.png",
    life: {
      exists: "pending",
    },
  },
  "Gliese 667 C f": {
    systemName: "Gliese 667 System",
    systemType: "Triple",
    parentStar: "Gliese 667 C",
    spectralClass: "M1.5V",
    distToSun: 15.42,
    type: "Planet",
    sma: 0.156,
    radius: 8489.5,
    mass: 2.7047,
    moonCount: 0,
    thumbnail: "img/promising/gj667cf.png",
    life: {
      exists: "pending",
    },
  },
  "Wolf 1069 b": {
    systemName: "Wolf 1069 System",
    systemType: "Single",
    parentStar: "Wolf 1069",
    spectralClass: "M5V",
    distToSun: 10.45,
    type: "Planet",
    sma: 0.0672,
    radius: 8267.29,
    mass: 1.260072,
    moonCount: 0,
    thumbnail: "img/promising/wolf1069b.png",
    life: {
      exists: "pending",
    },
  },
  "Gliese 12 b": {
    systemName: "Gliese 12 System",
    systemType: "Single",
    parentStar: "Gliese 12",
    spectralClass: "M3V",
    distToSun: 16.86,
    type: "Planet",
    sma: 0.066,
    radius: 5749.04,
    mass: 0.708782,
    moonCount: 0,
    thumbnail: "img/promising/gj12b.png",
    life: {
      exists: "pending",
    },
  },
  "TRAPPIST-1 d": {
    systemName: "TRAPPIST-1 System",
    systemType: "Single",
    parentStar: "TRAPPIST-1",
    spectralClass: "M8V",
    distToSun: 15.53,
    type: "Planet",
    sma: 0.02227,
    radius: 5020.35,
    mass: 0.388,
    moonCount: 0,
    thumbnail: "img/promising/trappist1d.png",
    life: {
      exists: "pending",
    },
  },
  "TRAPPIST-1 e": {
    systemName: "TRAPPIST-1 System",
    systemType: "Single",
    parentStar: "TRAPPIST-1",
    spectralClass: "M8V",
    distToSun: 15.53,
    type: "Planet",
    sma: 0.02925,
    radius: 5852.32,
    mass: 0.692,
    moonCount: 0,
    thumbnail: "img/promising/trappist1e.png",
    life: {
      exists: "pending",
    },
  },
  "TRAPPIST-1 f": {
    systemName: "TRAPPIST-1 System",
    systemType: "Single",
    parentStar: "TRAPPIST-1",
    spectralClass: "M8V",
    distToSun: 15.53,
    type: "Planet",
    sma: 0.03849,
    radius: 6634.37,
    mass: 1.039,
    moonCount: 0,
    thumbnail: "img/promising/trappist1f.png",
    life: {
      exists: "pending",
    },
  },
  "TRAPPIST-1 g": {
    systemName: "TRAPPIST-1 System",
    systemType: "Single",
    parentStar: "TRAPPIST-1",
    spectralClass: "M8V",
    distToSun: 15.53,
    type: "Planet",
    sma: 0.03849,
    radius: 7185.79,
    mass: 1.321,
    moonCount: 0,
    thumbnail: "img/promising/trappist1g.png",
    life: {
      exists: "pending",
    },
  },
  Najma: {
    altName: "Majriti VI",
    systemName: "Upsilon Andromedae System",
    systemType: "Binary",
    parentStar: "Titawin",
    spectralClass: "F8V",
    distToSun: 18.42,
    type: "Moon",
    parent: "Majriti",
    sma: 0.02250615349166,
    radius: 6714.81,
    mass: 1.15805137,
    moonCount: 0,
    thumbnail: "img/promising/najma.png",
    life: {
      exists: "pending",
    },
  },
  "LHS 1140 b": {
    systemName: "LHS 1140 System",
    systemType: "Single",
    parentStar: "LHS 1140",
    spectralClass: "M4.5V",
    distToSun: 20.01,
    type: "Planet",
    sma: 0.0946,
    radius: 11022,
    mass: 5.6,
    moonCount: 0,
    thumbnail: "img/promising/lhs1140b.png",
    life: {
      exists: "pending",
    },
  },
  "TOI-1452 b": {
    systemName: "TOI-1452 System",
    systemType: "Single",
    parentStar: "TOI-1452",
    spectralClass: "M4V",
    distToSun: 29.92,
    type: "Planet",
    sma: 0.061,
    radius: 10664.25,
    mass: 4.82,
    moonCount: 0,
    thumbnail: "img/promising/toi1452b.png",
    life: {
      exists: "pending",
    },
  },
  "TOI-700 e": {
    systemName: "TOI-700 System",
    systemType: "Single",
    parentStar: "TOI-700",
    spectralClass: "M2V",
    distToSun: 34.01,
    type: "Planet",
    sma: 0.134,
    radius: 6056.47,
    mass: 0.43869,
    moonCount: 0,
    thumbnail: "img/promising/toi700e.png",
    life: {
      exists: "pending",
    },
  },
  "TOI-700 d": {
    systemName: "TOI-700 System",
    systemType: "Single",
    parentStar: "TOI-700",
    spectralClass: "M2V",
    distToSun: 34.01,
    type: "Planet",
    sma: 0.1633,
    radius: 6820.91,
    mass: 2.415579,
    moonCount: 0,
    thumbnail: "img/promising/toi700d.png",
    life: {
      exists: "pending",
    },
  },
  "LP 890-9 c": {
    systemName: "LP 890-9 System",
    systemType: "Single",
    parentStar: "LP 890-9",
    spectralClass: "M6V",
    distToSun: 38.4,
    type: "Planet",
    sma: 0.03984,
    radius: 8698.96,
    mass: 25.32872,
    moonCount: 0,
    thumbnail: "img/promising/lp8909c.png",
    life: {
      exists: "pending",
    },
  },
  "TOI-715 b": {
    systemName: "TOI-715 System",
    systemType: "Single",
    parentStar: "TOI-1452",
    spectralClass: "M4V",
    distToSun: 44.11,
    type: "Planet",
    sma: 0.083,
    radius: 9837.41,
    mass: 1.3666,
    moonCount: 0,
    thumbnail: "img/promising/toi715b.png",
    life: {
      exists: "pending",
    },
  },
  "Kepler-1649 c": {
    systemName: "Kepler-1649 System",
    systemType: "Single",
    parentStar: "Kepler-1649",
    spectralClass: "M5V",
    distToSun: 89.56,
    type: "Planet",
    sma: 0.0830175519,
    radius: 6763.45,
    mass: 0.6285,
    moonCount: 0,
    thumbnail: "img/promising/kepler1649c.png",
    life: {
      exists: "pending",
    },
  },
  "Kepler-186 f": {
    systemName: "Kepler-186 System",
    systemType: "Single",
    parentStar: "Kepler-186",
    spectralClass: "M1V",
    distToSun: 176.07,
    type: "Planet",
    sma: 0.432,
    radius: 7426.53,
    mass: 1.44,
    moonCount: 0,
    thumbnail: "img/promising/kepler186f.png",
    life: {
      exists: "pending",
    },
  },
  "Kepler-296 A e": {
    systemName: "Kepler-296 System",
    systemType: "Binary",
    parentStar: "Kepler-296 A",
    spectralClass: "M1V",
    distToSun: 223.03,
    type: "Planet",
    sma: 0.174,
    radius: 11152.75,
    mass: 5.7548,
    moonCount: 0,
    thumbnail: "img/promising/kepler296ae.png",
    life: {
      exists: "pending",
    },
  },
  "Kepler-1652 b": {
    systemName: "Kepler-1652 System",
    systemType: "Single",
    parentStar: "Kepler-1652",
    spectralClass: "M2V",
    distToSun: 249.52,
    type: "Planet",
    sma: 0.1654,
    radius: 10214.71,
    mass: 4.3151,
    moonCount: 0,
    thumbnail: "img/promising/kepler1652b.png",
    life: {
      exists: "pending",
    },
  },
  Celis: {
    systemName: "Nexus System",
    systemType: "Octuple",
    parentStar: "Nexus Aa, Ab",
    spectralClass: "G8V, K2V",
    distToSun: 301.58,
    type: "Planet",
    sma: 1.08022,
    radius: 6371,
    mass: 1,
    moonCount: 9,
    thumbnail: "img/promising/celis.png",
    life: {
      exists: "pending",
    },
  },
  Diego: {
    altName: "Astrus II",
    systemName: "Nexus System",
    systemType: "Octuple",
    parentStar: "Nexus Aa, Ab",
    spectralClass: "G8V, K2V",
    distToSun: 301.58,
    type: "Moon",
    parent: "Astrus",
    sma: 0.00397,
    radius: 4211.0477318598105,
    mass: 0.21577915,
    moonCount: 0,
    thumbnail: "img/promising/diego.png",
    life: {
      exists: "pending",
    },
  },
  "Nexus Legendary": {
    systemName: "Nexus System",
    systemType: "Octuple",
    parentStar: "Nexus Ba, Bb",
    spectralClass: "K5V, M2V",
    distToSun: 301.58,
    type: "Planet",
    sma: 0.44,
    radius: 12028.780905448986,
    mass: 10.5262604,
    moonCount: 77,
    thumbnail: "img/promising/nexuslegendary.png",
    life: {
      exists: "pending",
    },
  },
  "KOI-4878.01": {
    systemName: "KOI-4878 System",
    systemType: "Single",
    parentStar: "KOI-4878",
    spectralClass: "G6V",
    distToSun: 341.39,
    type: "Planet",
    sma: 1.1392,
    radius: 6498.04,
    mass: 0.53457,
    moonCount: 0,
    thumbnail: "img/promising/koi4878.01.png",
    life: {
      exists: "pending",
    },
  },
  "Kepler-62 e": {
    systemName: "Kepler-62 System",
    systemType: "Single",
    parentStar: "Kepler-62",
    spectralClass: "M0V",
    distToSun: 364.57,
    type: "Planet",
    sma: 0.4277330796,
    radius: 11911.19,
    mass: 14.476,
    moonCount: 0,
    thumbnail: "img/promising/kepler62e.png",
    life: {
      exists: "pending",
    },
  },
  "Kepler-62 f": {
    systemName: "Kepler-62 System",
    systemType: "Single",
    parentStar: "Kepler-62",
    spectralClass: "M0V",
    distToSun: 364.57,
    type: "Planet",
    sma: 0.7199991667,
    radius: 9806.71,
    mass: 1.8132,
    moonCount: 0,
    thumbnail: "img/promising/kepler62f.png",
    life: {
      exists: "pending",
    },
  },
  "Kepler-442 b": {
    systemName: "Kepler-442 System",
    systemType: "Single",
    parentStar: "Kepler-442",
    spectralClass: "KV",
    distToSun: 366.37,
    type: "Planet",
    sma: 0.409,
    radius: 8535.85,
    mass: 2.3,
    moonCount: 0,
    thumbnail: "img/promising/kepler442b.png",
    life: {
      exists: "pending",
    },
  },
  Pyron: {
    systemName: "Vesper System",
    systemType: "Single",
    parentStar: "Vesper",
    spectralClass: "G5V",
    distToSun: 493.28,
    type: "Planet",
    sma: 1.2,
    radius: 11877.138541326127,
    mass: 10.0430927,
    moonCount: 8,
    thumbnail: "img/promising/pyron.png",
    life: {
      exists: "pending",
    },
  },
  Orval: {
    systemName: "Nebulous System",
    systemType: "Single",
    parentStar: "Nebulous",
    spectralClass: "M5.9V",
    distToSun: 594.98,
    type: "Planet",
    sma: 0.0215,
    radius: 5512.631087959769,
    mass: 0.585096,
    moonCount: 0,
    thumbnail: "img/promising/orval.png",
    life: {
      exists: "pending",
    },
  },
  Satyr: {
    systemName: "Lilith System",
    systemType: "Quadruple",
    parentStar: "Khepri",
    spectralClass: "K8.2V",
    distToSun: 862760.026,
    type: "Planet",
    sma: 0.415260489,
    radius: 9125.750823373657,
    mass: 3.78445816,
    moonCount: 0,
    thumbnail: "img/promising/satyr.png",
    life: {
      exists: "pending",
    },
  },
  Drakara: {
    systemName: "Keryx System",
    systemType: "Triple",
    parentStar: "Sentinel",
    spectralClass: "K4.4V",
    distToSun: 38035958.5,
    type: "Planet",
    sma: 0.313517529,
    radius: 6371,
    mass: 1,
    moonCount: 6,
    thumbnail: "img/promising/drakara.png",
    life: {
      exists: "pending",
    },
  },
  Altan: {
    systemName: "Keryx System",
    systemType: "Triple",
    parentStar: "Sentinel",
    spectralClass: "K4.4V",
    distToSun: 38035958.5,
    type: "Planet",
    sma: 0.415260489,
    radius: 6229.171969104664,
    mass: 0.920000017,
    moonCount: 1,
    thumbnail: "img/promising/altan.png",
    life: {
      exists: "pending",
    },
  },
  Vague: {
    systemName: "Void System",
    systemType: "Binary",
    parentStar: "Void",
    spectralClass: "X",
    distToSun: 38105993.3,
    type: "Planet",
    sma: 47.3431429,
    radius: 9251.684939805746,
    mass: 3.98152089,
    moonCount: 2,
    thumbnail: "img/promising/vague.png",
    life: {
      exists: "pending",
    },
  },
  Verdant: {
    systemName: "Void System",
    systemType: "Binary",
    parentStar: "Essence",
    spectralClass: "G8.8V",
    distToSun: 38105993.3,
    type: "Planet",
    sma: 0.7,
    radius: 5218.81317041712,
    mass: 0.477668345,
    moonCount: 0,
    thumbnail: "img/promising/verdant.png",
    life: {
      exists: "pending",
    },
  },
};

// ── TERRAFORMED WORLDS ───────────────────────────────────────
const TERRAFORMED_WORLDS = {
  Pholion: {
    altName: "Boreas I",
    systemName: "Nexus System",
    systemType: "Octuple",
    parentStar: "Nexus B",
    spectralClass: "K3V",
    distToSun: 301.58,
    type: "Moon",
    parent: "Boreas",
    sma: 0.008000000029412,
    radius: 5830.252705016458,
    mass: 0.74,
    moonCount: 0,
    thumbnail: "img/terraformed/pholion.png",
    life: {
      exists: "pending",
    },
  },
};
